services:
  - type: web
    name: api-estres-hidrico
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    region: oregon
    pythonVersion: 3.10.13